name: "Branch Push Lint & Test"

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest

    env:
      DISABLE_BOOTSNAP: true
      DISABLE_BOOTSNAP_LOAD_PATH_CACHE: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run linters
        run: bundle exec rubocop --parallel
      - name: Ruby security checks
        run: |
          bundle exec bundler-audit --update
          bundle exec brakeman -q -w2

  test:
    name: Tests
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432
      DISABLE_BOOTSNAP: true
      DISABLE_BOOTSNAP_LOAD_PATH_CACHE: true

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Create database
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load

      - name: Factory lint
        run: bundle exec rake factory_bot:lint

      - name: Run tests
        run: bundle exec rake
  
  deploy:
    name: Deploy to Heroku
    needs: [linters, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: false
          fetch-depth: 0
      
      - name: 'Rename prod Dockerfile' # Action does not support specifying Dockerfile yet
        run: |
          cp Dockerfile.web Dockerfile

      - name: Heroku Docker Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "evaluate-me-prod"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          justlogin: true

      - name: Login to Heroku Container Registry
        run: |
          heroku container:login
      - name: Build and Push image
        run: |
          heroku container:push web --recursive -a evaluate-me-prod
      - name: Release image
        run: |
          heroku container:release web -a evaluate-me-prod

